export interface Challenge {
  name: string,
  score: number
}

export let challenges:Array<Challenge> = [
  { name: 'Walk up to a stranger, point to the speaker/ceiling and say, "I love Brian McKnight.”', score: 1 },
  { name: 'Ask a stranger to catsit.', score: 1 },
  { name: 'Slip the phrase “Dance like nobody’s watching” into a conversation with a stranger.', score: 1 },
  { name: 'Drop the line “I was VIP at Coachella” into a conversation with a stranger.', score: 1 },
  { name: 'Walk up to the tallest person at the bar and scoff, “I’ve seen taller."', score: 1 },
  { name: 'Walk up to a stranger, look into your drink, and sigh: “Sad about Princess Di, right?”', score: 1 },
  { name: 'Walk up to a stranger, touch their shoulder, widen your eyes and say, “When’s the last time you did something for the first time?”', score: 1 },
  { name: 'Walk up to the smokers and say, “So are we inhaling?”', score: 1 },
  { name: 'Mouth the conversation of a stranger you’re not talking to.', score: 1 },
  { name: 'Try to do the Tim Allen grunt and get someone to recognize it.', score: 1 },
  { name: 'Do a terrible Jim Carrey impression for a stranger.', score: 1 },
  { name: 'Ask to borrow someone’s eyeglasses, explaining that you forgot yours at home and you can’t read the menu.', score: 1 },
  { name: 'Say the phrase “We are stronger than the storm” during a conversation with a stranger.', score: 1 },
  { name: 'While shaking a stranger’s hand, tickle their palm with your index finger. Until they notice.', score: 1 },
  { name: 'Order a warm glass of milk for yourself and have another sent to a stranger. Await visual confirmation. Long-distance cheers.', score: 1 },


  { name: 'Walk up to a stranger, point at them, and jump right in: “Bill Cosby: innocent?”', score: 2 },
  { name: 'Ask a stranger what’s in a whiskey & gingerale. Then ask about a vodka & tonic.', score: 2 },
  { name: 'As you pass a stranger, stop and say, "See ya later, alligator." Don’t leave until they respond, “after while, crocodile.”', score: 2 },
  { name: 'Tell a stranger you have a secret. Wait for them to ask what it is, then refuse to tell them on the grounds that it’s a secret.', score: 2 },
  { name: 'Get super stoked about a stranger’s drink order.', score: 2 },
  { name: 'Walk over to a group of people and hold your hand to your head like it\'s a phone. Now use it to angrily be broken up with by your significant other.', score: 2 },
  { name: 'Walk over to a group and excitedly have them get together for a photo. Take the photo. Walk away.', score: 2 },
  { name: 'Walk the most crowded route from one side of the bar to the other, loudly saying “behind!” every time you walk behind someone.', score: 2 },
  { name: 'Walk up to a group and then emphatically laugh after an arbitrary sentence.', score: 2 },
  { name: 'Go up to a group consisting only of the opposite sex and say, “What are we talking about?”', score: 2 },
  { name: 'Point at 5 different nearby strangers in rapid succession and say “Coffee?!” each time.', score: 2 },
  { name: 'Become the hype man for a stranger, complete with air horns and gun shots.', score: 2 },
  { name: 'Do the Home Alone scream + face to a stranger.', score: 2 },
  { name: 'Sing the entire name gam song with a stranger’s name immediately after introduction.', score: 2 },
  { name: 'Make the following comment to a stranger: “This bar is so erotic tonight”', score: 2 },


  { name: 'Stand at the front of the bar as if you’re the host. When the next person comes in, ask how many is in their party. No matter what, turn behind you and scream “Party of 5!” Walk away.', score: 3 },
  { name: 'Ask a stranger if they left their ID at your house last night.', score: 3 },
  { name: 'Introduce yourself to a group of strangers, then immediately go silent for a full minute. Gestures are okay.', score: 3 },
  { name: 'Continually say “excuse me” as you walk around with your arms stiffly outstretched directy in front of you for 15 seconds.', score: 3 },
  { name: 'Lock eyes with a stranger and dance like a madman.', score: 3 },
  { name: 'Try to communicate to a stranger in only gestures.', score: 3 },
  { name: 'Ask to borrow a stranger’s hat, explaining that it’s to hide yourself from your ex as you walk to the bathroom. Create backstory as necessary.', score: 3 },
  { name: 'Ask someone to take a photo of you. On their phone. Don’t let them send it to you.', score: 3 },
  { name: 'Get a stranger to give you a neck mssage. (Braggin rights: From the front.)', score: 3 },
  { name: 'Ask someone if they’ll catch you in a trust fall. Then do it.”', score: 3 },
  { name: 'Walk over to a group sitting at a table with a candle. Blow out the candle and back away slowly. Never speak.', score: 3 },
  { name: 'Take an empty beer can over to a group of strangers. Crush the can between your hands. Raise you arms into “what now?” position. Walk away.', score: 3 },
  { name: 'Unbutton the top button of a stranger\'s shirt without explanation.', score: 3 },
  { name: 'Ask a stranger if you can taste their drink. When they say yes, reveal your super straw, constructed out of five or more regular straws. Drink up.', score: 3 },
  { name: 'Sip a stranger’s drink without asking them.', score: 3 }]; 